version: '3.8'
services:
  backend:
    build: .
    container_name: ecommerce-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    command: pnpm start:prod
  mongo:
    image: mongo:6
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
